-- ui/templates.lua
-- NOTE: this file is never autogenerated nor overwritten by NEXUS.

default_scale_type = "RELATIVE_TO_SCREEN_SIZE";
default_position_type = "RELATIVE_TO_PARENT";

--
--         DEFAULT Components
--         ------------------
--
-- You are required to have Default components for each component type.
-- All names MUST be "Default*", where * is the component name, first letter
-- in upper case (eg. "DefaultButton").
--

-- Label component is removed: use either Textbox, Image, Rectangle, or Marker instead.

CreateComp ("Textbox", "DefaultTextbox");
SetProperty ("textbox.font", "fonts/small.mft");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);

CreateComp ("Image", "DefaultImage");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);

CreateComp ("Marker", "DefaultMarker");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("Rectangle", "DefaultRectangle");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("Ruler", "DefaultRuler");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("ruler.endpoint_bitmap", "ui/gfx/ruler_endpoint.png");
SetProperty ("ruler.repeat_bitmap", "ui/gfx/ruler_repeat.png");
SetProperty ("ruler.client_width", 300);
SetProperty ("ruler.client_height", 63.500000);

CreateComp ("Button", "DefaultButton");
SetProperty ("snd_over", "sfx/button-over"); -- note that this attribute is for all component types
SetProperty ("snd_press", "sfx/button-press");
--SetProperty ("snd_release", "sfx/button-press");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-medium-idle.png");
SetProperty ("button.bm_over", "ui/gfx/button-medium-idle.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-medium-idle.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-medium-idle.png");
SetProperty ("button.scale_pressed", 0.975);
SetProperty ("button.scale_idle", 1.00);
SetProperty ("button.scale_over", 1.01);
SetProperty ("button.scale_disabled", 1.00);
SetProperty ("button.bitmap_color_disabled", 1,1,1,0.6);
SetProperty ("button.text_color_disabled", 1,1,1,0.6);
SetProperty ("button.text_scale_pressed", 0.975);
SetProperty ("button.text_scale_over", 1);
SetProperty ("button.text_offset", 0, 0);
SetProperty ("button.max_text_width_percentage", 86);

SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);


CreateComp ("Slider", "DefaultSlider");
SetProperty ("snd_over", "sfx/button-over");
SetProperty ("slider.bm_panel", "ui/gfx/slider-panel.png");
SetProperty ("slider.bm_panel_over", "!NONE");--ui/gfx/slider-panel-over.png");
SetProperty ("slider.bm_full", "ui/gfx/slider-full.png");
SetProperty ("slider.bm_marker", "ui/gfx/slider-marker.png");
SetProperty ("slider.padding", 21, 23);
SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);


CreateComp ("Editbox", "DefaultEditbox");
SetProperty ("snd_over", "sfx/button-over");
SetProperty ("snd_press", "sfx/button-press");
SetProperty ("editbox.font", "fonts/small.mft");
SetProperty ("editbox.bm_cursor", "ui/gfx/editbox-cursor.png");
SetProperty ("editbox.bm_panel", "ui/gfx/editbox-panel.png");
SetProperty ("editbox.bm_panel_over", "ui/gfx/editbox-panel.png");
SetProperty ("editbox.padding", 8); -- pixels to pad on left and right
SetProperty ("editbox.max_chars", 32);
SetProperty ("editbox.text_scale", 1.0);
SetProperty ("editbox.text_offset", 4, 2);
SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);


CreateComp ("Editbox", "EditboxShort");
SetProperty ("editbox.bm_panel", "ui/gfx/editbox-short-panel.png");
SetProperty ("editbox.bm_panel_over", "ui/gfx/editbox-short-panel.png");

CreateComp ("Editbox", "EditboxWide");
SetProperty ("editbox.bm_panel", "ui/gfx/editbox-wide-panel.png");
SetProperty ("editbox.bm_panel_over", "ui/gfx/editbox-wide-panel.png");


CreateComp ("Checkbox", "DefaultCheckbox");
SetProperty ("snd_over", "sfx/button-over"); -- note that this attribute is for all component types
SetProperty ("snd_press", "sfx/button-press");
SetProperty ("checkbox.font", "fonts/small.mft");
SetProperty ("checkbox.bm_idle", "ui/gfx/checkbox-idle.png");
SetProperty ("checkbox.bm_over", "ui/gfx/checkbox-idle.png");
SetProperty ("checkbox.bm_pressed", "ui/gfx/checkbox-idle.png");
SetProperty ("checkbox.bm_disabled", "ui/gfx/checkbox-idle.png");
SetProperty ("checkbox.bm_marker", "ui/gfx/checkbox-marker.png");
SetProperty ("checkbox.padding_before_text", 8);
SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);


CreateComp ("Listbox", "DefaultListbox");
SetProperty ("snd_over", "!NONE");
SetProperty ("listbox.font", "fonts/small.mft");
SetProperty ("listbox.bm_frame", "ui/gfx/ninepatch-thin.png");
SetProperty ("listbox.bm_frame_top", "!NONE");
--SetProperty ("listbox.bm_selection", "ui/gfx/listbox_selector.png");
SetProperty ("listbox.padding_left", 20);
SetProperty ("listbox.padding_right", 20);
SetProperty ("listbox.padding_top", 15);
SetProperty ("listbox.padding_bottom", 15);
SetProperty ("listbox.ninepatch_margin", 43);
SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);


CreateComp ("Path", "DefaultPath");
--SetProperty ("path.point", -10, -10);


CreateComp ("Emitter", "DefaultEmitter");
SetProperty ("emitter.time_interval", 0.3);
SetProperty ("emitter.initial_simulation_time", 0.0);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);

CreateComp ("Scriptable", "DefaultScriptable");
SetProperty ("scriptable.script", "ui/custom/comp-default.lua");

local default_ninepatch_size = 200;
local default_ninepatch_margin_left_right = 12;
local default_ninepatch_margin_top_bottom = 32;

CreateComp ("NinePatch", "DefaultNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/ninepatch.png");
SetProperty ("ninepatch.bitmap_client_rect", default_ninepatch_margin_left_right, default_ninepatch_margin_top_bottom, default_ninepatch_size-default_ninepatch_margin_left_right, default_ninepatch_size-default_ninepatch_margin_top_bottom);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("NinePatch", "OpaqueNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/ninepatch-opaque.png");
SetProperty ("ninepatch.bitmap_client_rect", default_ninepatch_margin_left_right, default_ninepatch_margin_top_bottom, default_ninepatch_size-default_ninepatch_margin_left_right, default_ninepatch_size-default_ninepatch_margin_top_bottom);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("NinePatch", "ThinNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/ninepatch-thin.png");
SetProperty ("ninepatch.bitmap_client_rect", default_ninepatch_margin_left_right, default_ninepatch_margin_top_bottom, default_ninepatch_size-default_ninepatch_margin_left_right, default_ninepatch_size-default_ninepatch_margin_top_bottom);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("NinePatch", "BracketNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/ninepatch-thin.png");
SetProperty ("ninepatch.bitmap_client_rect", default_ninepatch_margin_left_right, default_ninepatch_margin_top_bottom, default_ninepatch_size-default_ninepatch_margin_left_right, default_ninepatch_size-default_ninepatch_margin_top_bottom);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("NinePatch", "SelectedNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/ninepatch-selected.png");
SetProperty ("ninepatch.bitmap_client_rect", 43, 43, 200-43, 200-43);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("NinePatch", "DarkenerNinePatch");
SetProperty ("ninepatch.bitmap", "ui/gfx/interlace_soft.png");
SetProperty ("ninepatch.bitmap_client_rect", 12, 12, 46-12, 26-12);
SetProperty ("ninepatch.client_size", 200, 200);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);


CreateComp ("TouchField", "DefaultTouchField");
SetProperty ("touchfield.area_width", 160);
SetProperty ("touchfield.area_height", 120);
SetProperty ("touchfield.content_width", 160);
SetProperty ("touchfield.content_height", 3*120);
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);


CreateComp ("TouchGrid", "DefaultTouchGrid");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("Model", "DefaultModel");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);

CreateComp ("DropDownList", "DefaultDropDownList");
SetProperty ("drop_down_list.font", "fonts/small.mft");
SetProperty ("drop_down_list.bm_ninepatch", "ui/editor/gfx/drop-down-list-ninepatch.png");
SetProperty ("drop_down_list.ninepatch_margin", 12);

--
--         Custom Components
--         -----------------
--
-- You can have as many custom templates for components as you want.
-- Note that all of these also inherit the values of Default Components.
--

CreateComp ("Textbox", "CreditsTitleTextbox");
SetProperty ("textbox.font", "fonts/large.mft");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);

CreateComp ("Textbox", "CreditsNameTextbox");
SetProperty ("textbox.font", "fonts/medium.mft");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("inherit_scale", true);

CreateComp ("Image", "GenericFullscreenPanel");
SetProperty ("position", 0.5, 0.5);
SetProperty ("scale_type", "FIT_TO_COVER_SCREEN");
SetProperty ("scale", 1.0);
SetProperty ("align", "CENTER");
SetProperty ("cache_mode", "LOAD_ON_ENTER_RELEASE_ON_LEAVE");
SetProperty ("image.bitmap", "ui/gfx/bg.png");


CreateComp ("Image", "GenericHorizontalRule");
SetProperty ("align", "CENTER");
SetProperty ("cache_mode", "LOAD_ON_ENTER_RELEASE_ON_LEAVE");
SetProperty ("image.bitmap", "ui/gfx/horizontal-ruler.png");


CreateComp ("Marker", "EditorPaletteItemMarker");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);
SetProperty ("marker.area_width", 50);
SetProperty ("marker.area_height", 50);
SetProperty ("align", "CENTER");
SetProperty ("custom_draw", 1);


CreateComp ("Listbox", "ListboxSmall");
SetProperty ("listbox.font", "fonts/small.mft");
SetProperty ("listbox.bm_frame", "ui/gfx/ninepatch-thin.png");
SetProperty ("listbox.bm_frame_top", "!NONE");
SetProperty ("listbox.bm_selection", "!NONE");
SetProperty ("listbox.padding_left", 10);
SetProperty ("listbox.padding_right", 10);
SetProperty ("listbox.padding_top", 10);
SetProperty ("listbox.padding_bottom", 10);
SetProperty ("listbox.ninepatch_margin", 10);
SetProperty ("align", "CENTER");
SetProperty ("scale_type", default_scale_type);
SetProperty ("position_type", default_position_type);



-- Fader rectangle meant for full screen overlays to make popup screen stand
-- out from the background better.
CreateComp ("Rectangle", "FaderRectangle");
SetProperty ("position", 0, 0);
SetProperty ("color.r", 0.0);
SetProperty ("color.g", 0.0);
SetProperty ("color.b", 0.0);
SetProperty ("color.a", 0.45);
--SetProperty ("blend_mode", "ADDITIVE");
SetProperty ("rectangle.rect_width", GetScreenWidth ());
SetProperty ("rectangle.rect_height", GetScreenHeight ());
SetProperty ("scale_type", "STRETCH_TO_COVER_SCREEN");

CreateComp ("Rectangle", "BlackBackground");
SetProperty ("position", 0, 0);
SetProperty ("color.r", 0.0);
SetProperty ("color.g", 0.0);
SetProperty ("color.b", 0.0);
SetProperty ("color.a", 1);
SetProperty ("rectangle.rect_width", GetScreenWidth ());
SetProperty ("rectangle.rect_height", GetScreenHeight ());
SetProperty ("scale_type", "FIT_TO_COVER_SCREEN");

CreateComp ("Rectangle", "DividerRectangle");
SetProperty ("position", 0, 0);
SetProperty ("color.r", 1);
SetProperty ("color.g", 0.3);
SetProperty ("color.b", 1);
SetProperty ("color.a", 0.6);
SetProperty ("align", "HCENTER");
SetProperty ("rectangle.rect_width", 270);
SetProperty ("rectangle.rect_height", 3);


CreateComp ("Image", "BackgroundImage");
SetProperty ("scale_type", "FIT_TO_COVER_SCREEN");--STRETCH_TO_COVER_SCREEN");
SetProperty ("position_type", default_position_type);
SetProperty ("position", 0.5, 0.5);
SetProperty ("align", "CENTER");
SetProperty ("image.bitmap", "ui/gfx/bg.png");


CreateComp ("Textbox", "SmallTextbox");
SetProperty ("textbox.font", "fonts/small.mft");

CreateComp ("Textbox", "MediumTextbox");
SetProperty ("textbox.font", "fonts/medium.mft");

CreateComp ("Textbox", "LargeTextbox");
SetProperty ("textbox.font", "fonts/large.mft");


CreateComp ("BUTTON", "SmallButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 18);
SetProperty ("button.ninepatch_width", 120);
SetProperty ("button.ninepatch_height", 60);


CreateComp ("BUTTON", "WideButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 18);
SetProperty ("button.ninepatch_width", 310);
SetProperty ("button.ninepatch_height", 48);


CreateComp ("BUTTON", "SmallSquareButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 24);
SetProperty ("button.ninepatch_width", 50);
SetProperty ("button.ninepatch_height", 50);
SetProperty ("expanded_hit_area", 10);


CreateComp ("BUTTON", "ResearchButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 24);
SetProperty ("button.ninepatch_width", 200);
SetProperty ("button.ninepatch_height", 120);
SetProperty ("button.icon_offset", 0, -14);
SetProperty ("button.text_offset", 0, 31);
SetProperty ("button.text_scale_pressed", 0.9);
SetProperty ("button.text_scale_over", 0.9);
SetProperty ("button.text_scale_idle", 0.9);
SetProperty ("scale", 0.8);


CreateComp ("BUTTON", "SmallSquareXButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 24);
SetProperty ("button.ninepatch_width", 50);
SetProperty ("button.ninepatch_height", 50);
SetProperty ("button.bm_icon", "ui/gfx/checkbox-marker.png");
SetProperty ("expanded_hit_area", 14);
--SetProperty ("button.text", "X");



CreateComp ("BUTTON", "SmallSquarePauseButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 24);
SetProperty ("button.ninepatch_width", 50);
SetProperty ("button.ninepatch_height", 50);
SetProperty ("localize", 0);
SetProperty ("button.text", "II");
SetProperty ("expanded_hit_area", 24);
SetProperty ("button.text_offset", 1, 0);

CreateComp ("BUTTON", "SmallSquareEditorButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 24);
SetProperty ("button.ninepatch_width", 50);
SetProperty ("button.ninepatch_height", 50);
SetProperty ("localize", 0);
SetProperty ("button.text", "E");
 

CreateComp ("BUTTON", "EnhancementButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 18);
SetProperty ("button.ninepatch_width", 60+18);
SetProperty ("button.ninepatch_height", 60+18);
SetProperty ("expanded_hit_area", 8);

CreateComp ("BUTTON", "MissionButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_over", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_pressed", "ui/gfx/button-ninepatch.png");
SetProperty ("button.bm_disabled", "ui/gfx/button-ninepatch.png");
SetProperty ("button.ninepatch_margin", 18);
SetProperty ("button.ninepatch_width", 36);
SetProperty ("button.ninepatch_height", 36);

CreateComp ("BUTTON", "NinepatchOpenButton");
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("button.bm_idle", "ui/gfx/ninepatch-top-open.png");
SetProperty ("button.bm_over", "ui/gfx/ninepatch-top-open.png");
SetProperty ("button.bm_pressed", "ui/gfx/ninepatch-top-open.png");
SetProperty ("button.bm_disabled", "ui/gfx/ninepatch-top-open.png");
SetProperty ("button.ninepatch_margin", 18);
SetProperty ("button.ninepatch_width", 36);
SetProperty ("button.ninepatch_height", 36);

CreateComp ("BUTTON", "MediumButton");

CreateComp ("BUTTON", "TextButton");
SetProperty ("button.bm_idle", "!NONE");
SetProperty ("button.bm_over", "!NONE");
SetProperty ("button.bm_pressed", "!NONE");
SetProperty ("button.bm_disabled", "!NONE");
SetProperty ("button.text_offset", 0, 0);
SetProperty ("button.font", "fonts/medium.mft");
SetProperty ("button.scale_pressed", 0.95);
SetProperty ("button.scale_over", 1.0);
SetProperty ("button.scale_disabled", 0.94);
SetProperty ("button.text_scale_pressed", 0.95);
SetProperty ("button.text_scale_over", 1);
SetProperty ("button.text_color_idle", 1,1,1,1);
SetProperty ("button.text_color_over", 1,0,0,1);
SetProperty ("button.text_color_pressed", 1,0,0,1);


CreateComp ("BUTTON", "TabIconButton");
SetProperty ("button.bm_idle", "!NONE");
SetProperty ("button.bm_over", "!NONE");
SetProperty ("button.bm_pressed", "!NONE");
SetProperty ("button.bm_disabled", "!NONE");
local default_scale = 1.1;
local pressed_scale = 1.05;
SetProperty ("button.scale_pressed", pressed_scale);
SetProperty ("button.scale_idle", default_scale);
SetProperty ("button.scale_over", default_scale);
SetProperty ("button.scale_disabled", 0.94);
SetProperty ("button.text_scale_pressed", pressed_scale);
SetProperty ("button.text_scale_idle", default_scale);
SetProperty ("button.text_scale_over", default_scale);
SetProperty ("button.text_color_idle", 1,1,1,1);
SetProperty ("button.text_color_over", 1,0,0,1);
SetProperty ("button.text_color_pressed", 1,0,0,1);
SetProperty ("button.bm_icon", "ui/gfx/button-map.png");
SetProperty ("button.text_offset", 0, 32);
SetProperty ("button.font", "fonts/small.mft");
SetProperty ("can_be_accessed_with_gamepads", 0);
SetProperty ("expanded_hit_area", 30);



LuaInclude("ui/editor/templates.lua");